env:
  browser: false
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      paths: ['src', 'lib']
      extensions: ['.js', '.ts']
rules:
  import/extensions:
    - error
    - ignorePackages: true
      pattern:
        ts: never
  import/prefer-default-export: off
  no-unused-vars:
    - 2
    - args: none
  max-len:
    - error
    - code: 120
      tabWidth: 2
      ignoreUrls: true
  object-curly-newline:
    - off
  no-await-in-loop:
    - off
  class-methods-use-this:
    - off
  lines-between-class-members:
    - error
    - always
    - exceptAfterSingleLine: true
  no-empty-function:
    - error
    - allow: ['constructors']
  no-useless-constructor:
    - off
